// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale?/collections/:handle" | "/:locale?/products/:handle" | "/:locale?";
  };
  "routes/($locale).collections.$handle.tsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/($locale).collections.$handle": typeof import("./app/routes/($locale).collections.$handle.tsx");
  "routes/($locale).products.$handle": typeof import("./app/routes/($locale).products.$handle.tsx");
  "routes/($locale)._index": typeof import("./app/routes/($locale)._index.tsx");
};