/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiChangelogRouteImport } from './routes/api/changelog'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleForTranslatorsRouteImport } from './routes/$locale/for-translators'
import { Route as LocaleForProductTeamsRouteImport } from './routes/$locale/for-product-teams'
import { Route as LocaleForDevelopersRouteImport } from './routes/$locale/for-developers'
import { Route as LocaleChangelogRouteImport } from './routes/$locale/changelog'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogRoute = ApiChangelogRouteImport.update({
  id: '/api/changelog',
  path: '/api/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/$locale/terms',
  path: '/$locale/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/$locale/privacy',
  path: '/$locale/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForTranslatorsRoute = LocaleForTranslatorsRouteImport.update({
  id: '/$locale/for-translators',
  path: '/$locale/for-translators',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForProductTeamsRoute = LocaleForProductTeamsRouteImport.update({
  id: '/$locale/for-product-teams',
  path: '/$locale/for-product-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForDevelopersRoute = LocaleForDevelopersRouteImport.update({
  id: '/$locale/for-developers',
  path: '/$locale/for-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleChangelogRoute = LocaleChangelogRouteImport.update({
  id: '/$locale/changelog',
  path: '/$locale/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/$locale/blog/',
  path: '/$locale/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/privacy'
    | '/terms'
    | '/$locale/changelog'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/changelog'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/privacy'
    | '/terms'
    | '/$locale/changelog'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/changelog'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/blog'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/privacy'
    | '/terms'
    | '/$locale/changelog'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/changelog'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LocaleChangelogRoute: typeof LocaleChangelogRoute
  LocaleForDevelopersRoute: typeof LocaleForDevelopersRoute
  LocaleForProductTeamsRoute: typeof LocaleForProductTeamsRoute
  LocaleForTranslatorsRoute: typeof LocaleForTranslatorsRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  ApiChangelogRoute: typeof ApiChangelogRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog': {
      id: '/api/changelog'
      path: '/api/changelog'
      fullPath: '/api/changelog'
      preLoaderRoute: typeof ApiChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/$locale/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/$locale/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-translators': {
      id: '/$locale/for-translators'
      path: '/$locale/for-translators'
      fullPath: '/$locale/for-translators'
      preLoaderRoute: typeof LocaleForTranslatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-product-teams': {
      id: '/$locale/for-product-teams'
      path: '/$locale/for-product-teams'
      fullPath: '/$locale/for-product-teams'
      preLoaderRoute: typeof LocaleForProductTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-developers': {
      id: '/$locale/for-developers'
      path: '/$locale/for-developers'
      fullPath: '/$locale/for-developers'
      preLoaderRoute: typeof LocaleForDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/changelog': {
      id: '/$locale/changelog'
      path: '/$locale/changelog'
      fullPath: '/$locale/changelog'
      preLoaderRoute: typeof LocaleChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/$locale/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LocaleChangelogRoute: LocaleChangelogRoute,
  LocaleForDevelopersRoute: LocaleForDevelopersRoute,
  LocaleForProductTeamsRoute: LocaleForProductTeamsRoute,
  LocaleForTranslatorsRoute: LocaleForTranslatorsRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  ApiChangelogRoute: ApiChangelogRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
