/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiChangelogRouteImport } from './routes/api/changelog'
import { Route as LocaleWhatIsLocalizationRouteImport } from './routes/$locale/what-is-localization'
import { Route as LocaleWhatIsInternationalizationRouteImport } from './routes/$locale/what-is-internationalization'
import { Route as LocaleWhatIsRouteImport } from './routes/$locale/what-is'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleStatusRouteImport } from './routes/$locale/status'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocaleIntegrationsRouteImport } from './routes/$locale/integrations'
import { Route as LocaleForTranslatorsRouteImport } from './routes/$locale/for-translators'
import { Route as LocaleForProductTeamsRouteImport } from './routes/$locale/for-product-teams'
import { Route as LocaleForDevelopersRouteImport } from './routes/$locale/for-developers'
import { Route as LocaleFeaturesRouteImport } from './routes/$locale/features'
import { Route as LocaleChangelogRouteImport } from './routes/$locale/changelog'
import { Route as LocaleCareersRouteImport } from './routes/$locale/careers'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleI18nIndexRouteImport } from './routes/$locale/i18n/index'
import { Route as LocaleCompareIndexRouteImport } from './routes/$locale/compare/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleI18nWebsiteTranslationRouteImport } from './routes/$locale/i18n/website-translation'
import { Route as LocaleI18nWebsiteLocalizationRouteImport } from './routes/$locale/i18n/website-localization'
import { Route as LocaleI18nVueRouteImport } from './routes/$locale/i18n/vue'
import { Route as LocaleI18nTranslationSolutionsRouteImport } from './routes/$locale/i18n/translation-solutions'
import { Route as LocaleI18nTranslationManagementSystemRouteImport } from './routes/$locale/i18n/translation-management-system'
import { Route as LocaleI18nTechnicalMultilingualSeoRouteImport } from './routes/$locale/i18n/technical-multilingual-seo'
import { Route as LocaleI18nTechnicalInternationalSeoRouteImport } from './routes/$locale/i18n/technical-international-seo'
import { Route as LocaleI18nSvelteRouteImport } from './routes/$locale/i18n/svelte'
import { Route as LocaleI18nSoftwareLocalizationServicesRouteImport } from './routes/$locale/i18n/software-localization-services'
import { Route as LocaleI18nSoftwareLocalizationRouteImport } from './routes/$locale/i18n/software-localization'
import { Route as LocaleI18nSeoInternationalAudiencesRouteImport } from './routes/$locale/i18n/seo-international-audiences'
import { Route as LocaleI18nReactIntlRouteImport } from './routes/$locale/i18n/react-intl'
import { Route as LocaleI18nReactRouteImport } from './routes/$locale/i18n/react'
import { Route as LocaleI18nNuxtRouteImport } from './routes/$locale/i18n/nuxt'
import { Route as LocaleI18nNextjsRouteImport } from './routes/$locale/i18n/nextjs'
import { Route as LocaleI18nMultilingualWebsiteSeoRouteImport } from './routes/$locale/i18n/multilingual-website-seo'
import { Route as LocaleI18nMultilingualSeoRouteImport } from './routes/$locale/i18n/multilingual-seo'
import { Route as LocaleI18nLocalizationVsInternationalizationRouteImport } from './routes/$locale/i18n/localization-vs-internationalization'
import { Route as LocaleI18nLocalizationToolsRouteImport } from './routes/$locale/i18n/localization-tools'
import { Route as LocaleI18nLocalizationSoftwareRouteImport } from './routes/$locale/i18n/localization-software'
import { Route as LocaleI18nLocalizationPlatformsRouteImport } from './routes/$locale/i18n/localization-platforms'
import { Route as LocaleI18nLocalizationManagementRouteImport } from './routes/$locale/i18n/localization-management'
import { Route as LocaleI18nLocalSeoInternationalRouteImport } from './routes/$locale/i18n/local-seo-international'
import { Route as LocaleI18nInternationalSeoConsultingRouteImport } from './routes/$locale/i18n/international-seo-consulting'
import { Route as LocaleI18nInternationalSeoRouteImport } from './routes/$locale/i18n/international-seo'
import { Route as LocaleI18nGlobalMarketSeoRouteImport } from './routes/$locale/i18n/global-market-seo'
import { Route as LocaleI18nForDevelopersRouteImport } from './routes/$locale/i18n/for-developers'
import { Route as LocaleI18nEcommerceGlobalSeoRouteImport } from './routes/$locale/i18n/ecommerce-global-seo'
import { Route as LocaleI18nCulturalAdaptationRouteImport } from './routes/$locale/i18n/cultural-adaptation'
import { Route as LocaleI18nContentLocalizationServicesRouteImport } from './routes/$locale/i18n/content-localization-services'
import { Route as LocaleI18nContentLocalizationRouteImport } from './routes/$locale/i18n/content-localization'
import { Route as LocaleI18nBestTmsRouteImport } from './routes/$locale/i18n/best-tms'
import { Route as LocaleI18nBestLibraryRouteImport } from './routes/$locale/i18n/best-library'
import { Route as LocaleI18nAngularRouteImport } from './routes/$locale/i18n/angular'
import { Route as LocaleCompareTransifexRouteImport } from './routes/$locale/compare/transifex'
import { Route as LocaleComparePhraseRouteImport } from './routes/$locale/compare/phrase'
import { Route as LocaleCompareLokaliseRouteImport } from './routes/$locale/compare/lokalise'
import { Route as LocaleCompareCrowdinRouteImport } from './routes/$locale/compare/crowdin'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogRoute = ApiChangelogRouteImport.update({
  id: '/api/changelog',
  path: '/api/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWhatIsLocalizationRoute =
  LocaleWhatIsLocalizationRouteImport.update({
    id: '/$locale/what-is-localization',
    path: '/$locale/what-is-localization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWhatIsInternationalizationRoute =
  LocaleWhatIsInternationalizationRouteImport.update({
    id: '/$locale/what-is-internationalization',
    path: '/$locale/what-is-internationalization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWhatIsRoute = LocaleWhatIsRouteImport.update({
  id: '/$locale/what-is',
  path: '/$locale/what-is',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/$locale/terms',
  path: '/$locale/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleStatusRoute = LocaleStatusRouteImport.update({
  id: '/$locale/status',
  path: '/$locale/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/$locale/privacy',
  path: '/$locale/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/$locale/pricing',
  path: '/$locale/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIntegrationsRoute = LocaleIntegrationsRouteImport.update({
  id: '/$locale/integrations',
  path: '/$locale/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForTranslatorsRoute = LocaleForTranslatorsRouteImport.update({
  id: '/$locale/for-translators',
  path: '/$locale/for-translators',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForProductTeamsRoute = LocaleForProductTeamsRouteImport.update({
  id: '/$locale/for-product-teams',
  path: '/$locale/for-product-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForDevelopersRoute = LocaleForDevelopersRouteImport.update({
  id: '/$locale/for-developers',
  path: '/$locale/for-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFeaturesRoute = LocaleFeaturesRouteImport.update({
  id: '/$locale/features',
  path: '/$locale/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleChangelogRoute = LocaleChangelogRouteImport.update({
  id: '/$locale/changelog',
  path: '/$locale/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCareersRoute = LocaleCareersRouteImport.update({
  id: '/$locale/careers',
  path: '/$locale/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nIndexRoute = LocaleI18nIndexRouteImport.update({
  id: '/$locale/i18n/',
  path: '/$locale/i18n/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCompareIndexRoute = LocaleCompareIndexRouteImport.update({
  id: '/$locale/compare/',
  path: '/$locale/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/$locale/blog/',
  path: '/$locale/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nWebsiteTranslationRoute =
  LocaleI18nWebsiteTranslationRouteImport.update({
    id: '/$locale/i18n/website-translation',
    path: '/$locale/i18n/website-translation',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nWebsiteLocalizationRoute =
  LocaleI18nWebsiteLocalizationRouteImport.update({
    id: '/$locale/i18n/website-localization',
    path: '/$locale/i18n/website-localization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nVueRoute = LocaleI18nVueRouteImport.update({
  id: '/$locale/i18n/vue',
  path: '/$locale/i18n/vue',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nTranslationSolutionsRoute =
  LocaleI18nTranslationSolutionsRouteImport.update({
    id: '/$locale/i18n/translation-solutions',
    path: '/$locale/i18n/translation-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nTranslationManagementSystemRoute =
  LocaleI18nTranslationManagementSystemRouteImport.update({
    id: '/$locale/i18n/translation-management-system',
    path: '/$locale/i18n/translation-management-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nTechnicalMultilingualSeoRoute =
  LocaleI18nTechnicalMultilingualSeoRouteImport.update({
    id: '/$locale/i18n/technical-multilingual-seo',
    path: '/$locale/i18n/technical-multilingual-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nTechnicalInternationalSeoRoute =
  LocaleI18nTechnicalInternationalSeoRouteImport.update({
    id: '/$locale/i18n/technical-international-seo',
    path: '/$locale/i18n/technical-international-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nSvelteRoute = LocaleI18nSvelteRouteImport.update({
  id: '/$locale/i18n/svelte',
  path: '/$locale/i18n/svelte',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nSoftwareLocalizationServicesRoute =
  LocaleI18nSoftwareLocalizationServicesRouteImport.update({
    id: '/$locale/i18n/software-localization-services',
    path: '/$locale/i18n/software-localization-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nSoftwareLocalizationRoute =
  LocaleI18nSoftwareLocalizationRouteImport.update({
    id: '/$locale/i18n/software-localization',
    path: '/$locale/i18n/software-localization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nSeoInternationalAudiencesRoute =
  LocaleI18nSeoInternationalAudiencesRouteImport.update({
    id: '/$locale/i18n/seo-international-audiences',
    path: '/$locale/i18n/seo-international-audiences',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nReactIntlRoute = LocaleI18nReactIntlRouteImport.update({
  id: '/$locale/i18n/react-intl',
  path: '/$locale/i18n/react-intl',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nReactRoute = LocaleI18nReactRouteImport.update({
  id: '/$locale/i18n/react',
  path: '/$locale/i18n/react',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nNuxtRoute = LocaleI18nNuxtRouteImport.update({
  id: '/$locale/i18n/nuxt',
  path: '/$locale/i18n/nuxt',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nNextjsRoute = LocaleI18nNextjsRouteImport.update({
  id: '/$locale/i18n/nextjs',
  path: '/$locale/i18n/nextjs',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nMultilingualWebsiteSeoRoute =
  LocaleI18nMultilingualWebsiteSeoRouteImport.update({
    id: '/$locale/i18n/multilingual-website-seo',
    path: '/$locale/i18n/multilingual-website-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nMultilingualSeoRoute =
  LocaleI18nMultilingualSeoRouteImport.update({
    id: '/$locale/i18n/multilingual-seo',
    path: '/$locale/i18n/multilingual-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalizationVsInternationalizationRoute =
  LocaleI18nLocalizationVsInternationalizationRouteImport.update({
    id: '/$locale/i18n/localization-vs-internationalization',
    path: '/$locale/i18n/localization-vs-internationalization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalizationToolsRoute =
  LocaleI18nLocalizationToolsRouteImport.update({
    id: '/$locale/i18n/localization-tools',
    path: '/$locale/i18n/localization-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalizationSoftwareRoute =
  LocaleI18nLocalizationSoftwareRouteImport.update({
    id: '/$locale/i18n/localization-software',
    path: '/$locale/i18n/localization-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalizationPlatformsRoute =
  LocaleI18nLocalizationPlatformsRouteImport.update({
    id: '/$locale/i18n/localization-platforms',
    path: '/$locale/i18n/localization-platforms',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalizationManagementRoute =
  LocaleI18nLocalizationManagementRouteImport.update({
    id: '/$locale/i18n/localization-management',
    path: '/$locale/i18n/localization-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nLocalSeoInternationalRoute =
  LocaleI18nLocalSeoInternationalRouteImport.update({
    id: '/$locale/i18n/local-seo-international',
    path: '/$locale/i18n/local-seo-international',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nInternationalSeoConsultingRoute =
  LocaleI18nInternationalSeoConsultingRouteImport.update({
    id: '/$locale/i18n/international-seo-consulting',
    path: '/$locale/i18n/international-seo-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nInternationalSeoRoute =
  LocaleI18nInternationalSeoRouteImport.update({
    id: '/$locale/i18n/international-seo',
    path: '/$locale/i18n/international-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nGlobalMarketSeoRoute =
  LocaleI18nGlobalMarketSeoRouteImport.update({
    id: '/$locale/i18n/global-market-seo',
    path: '/$locale/i18n/global-market-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nForDevelopersRoute = LocaleI18nForDevelopersRouteImport.update({
  id: '/$locale/i18n/for-developers',
  path: '/$locale/i18n/for-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nEcommerceGlobalSeoRoute =
  LocaleI18nEcommerceGlobalSeoRouteImport.update({
    id: '/$locale/i18n/ecommerce-global-seo',
    path: '/$locale/i18n/ecommerce-global-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nCulturalAdaptationRoute =
  LocaleI18nCulturalAdaptationRouteImport.update({
    id: '/$locale/i18n/cultural-adaptation',
    path: '/$locale/i18n/cultural-adaptation',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nContentLocalizationServicesRoute =
  LocaleI18nContentLocalizationServicesRouteImport.update({
    id: '/$locale/i18n/content-localization-services',
    path: '/$locale/i18n/content-localization-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nContentLocalizationRoute =
  LocaleI18nContentLocalizationRouteImport.update({
    id: '/$locale/i18n/content-localization',
    path: '/$locale/i18n/content-localization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleI18nBestTmsRoute = LocaleI18nBestTmsRouteImport.update({
  id: '/$locale/i18n/best-tms',
  path: '/$locale/i18n/best-tms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nBestLibraryRoute = LocaleI18nBestLibraryRouteImport.update({
  id: '/$locale/i18n/best-library',
  path: '/$locale/i18n/best-library',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleI18nAngularRoute = LocaleI18nAngularRouteImport.update({
  id: '/$locale/i18n/angular',
  path: '/$locale/i18n/angular',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCompareTransifexRoute = LocaleCompareTransifexRouteImport.update({
  id: '/$locale/compare/transifex',
  path: '/$locale/compare/transifex',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleComparePhraseRoute = LocaleComparePhraseRouteImport.update({
  id: '/$locale/compare/phrase',
  path: '/$locale/compare/phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCompareLokaliseRoute = LocaleCompareLokaliseRouteImport.update({
  id: '/$locale/compare/lokalise',
  path: '/$locale/compare/lokalise',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCompareCrowdinRoute = LocaleCompareCrowdinRouteImport.update({
  id: '/$locale/compare/crowdin',
  path: '/$locale/compare/crowdin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/features': typeof LocaleFeaturesRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/integrations': typeof LocaleIntegrationsRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/status': typeof LocaleStatusRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/what-is': typeof LocaleWhatIsRoute
  '/$locale/what-is-internationalization': typeof LocaleWhatIsInternationalizationRoute
  '/$locale/what-is-localization': typeof LocaleWhatIsLocalizationRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/status': typeof ApiStatusRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/compare/crowdin': typeof LocaleCompareCrowdinRoute
  '/$locale/compare/lokalise': typeof LocaleCompareLokaliseRoute
  '/$locale/compare/phrase': typeof LocaleComparePhraseRoute
  '/$locale/compare/transifex': typeof LocaleCompareTransifexRoute
  '/$locale/i18n/angular': typeof LocaleI18nAngularRoute
  '/$locale/i18n/best-library': typeof LocaleI18nBestLibraryRoute
  '/$locale/i18n/best-tms': typeof LocaleI18nBestTmsRoute
  '/$locale/i18n/content-localization': typeof LocaleI18nContentLocalizationRoute
  '/$locale/i18n/content-localization-services': typeof LocaleI18nContentLocalizationServicesRoute
  '/$locale/i18n/cultural-adaptation': typeof LocaleI18nCulturalAdaptationRoute
  '/$locale/i18n/ecommerce-global-seo': typeof LocaleI18nEcommerceGlobalSeoRoute
  '/$locale/i18n/for-developers': typeof LocaleI18nForDevelopersRoute
  '/$locale/i18n/global-market-seo': typeof LocaleI18nGlobalMarketSeoRoute
  '/$locale/i18n/international-seo': typeof LocaleI18nInternationalSeoRoute
  '/$locale/i18n/international-seo-consulting': typeof LocaleI18nInternationalSeoConsultingRoute
  '/$locale/i18n/local-seo-international': typeof LocaleI18nLocalSeoInternationalRoute
  '/$locale/i18n/localization-management': typeof LocaleI18nLocalizationManagementRoute
  '/$locale/i18n/localization-platforms': typeof LocaleI18nLocalizationPlatformsRoute
  '/$locale/i18n/localization-software': typeof LocaleI18nLocalizationSoftwareRoute
  '/$locale/i18n/localization-tools': typeof LocaleI18nLocalizationToolsRoute
  '/$locale/i18n/localization-vs-internationalization': typeof LocaleI18nLocalizationVsInternationalizationRoute
  '/$locale/i18n/multilingual-seo': typeof LocaleI18nMultilingualSeoRoute
  '/$locale/i18n/multilingual-website-seo': typeof LocaleI18nMultilingualWebsiteSeoRoute
  '/$locale/i18n/nextjs': typeof LocaleI18nNextjsRoute
  '/$locale/i18n/nuxt': typeof LocaleI18nNuxtRoute
  '/$locale/i18n/react': typeof LocaleI18nReactRoute
  '/$locale/i18n/react-intl': typeof LocaleI18nReactIntlRoute
  '/$locale/i18n/seo-international-audiences': typeof LocaleI18nSeoInternationalAudiencesRoute
  '/$locale/i18n/software-localization': typeof LocaleI18nSoftwareLocalizationRoute
  '/$locale/i18n/software-localization-services': typeof LocaleI18nSoftwareLocalizationServicesRoute
  '/$locale/i18n/svelte': typeof LocaleI18nSvelteRoute
  '/$locale/i18n/technical-international-seo': typeof LocaleI18nTechnicalInternationalSeoRoute
  '/$locale/i18n/technical-multilingual-seo': typeof LocaleI18nTechnicalMultilingualSeoRoute
  '/$locale/i18n/translation-management-system': typeof LocaleI18nTranslationManagementSystemRoute
  '/$locale/i18n/translation-solutions': typeof LocaleI18nTranslationSolutionsRoute
  '/$locale/i18n/vue': typeof LocaleI18nVueRoute
  '/$locale/i18n/website-localization': typeof LocaleI18nWebsiteLocalizationRoute
  '/$locale/i18n/website-translation': typeof LocaleI18nWebsiteTranslationRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/compare': typeof LocaleCompareIndexRoute
  '/$locale/i18n': typeof LocaleI18nIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/features': typeof LocaleFeaturesRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/integrations': typeof LocaleIntegrationsRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/status': typeof LocaleStatusRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/what-is': typeof LocaleWhatIsRoute
  '/$locale/what-is-internationalization': typeof LocaleWhatIsInternationalizationRoute
  '/$locale/what-is-localization': typeof LocaleWhatIsLocalizationRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/status': typeof ApiStatusRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/compare/crowdin': typeof LocaleCompareCrowdinRoute
  '/$locale/compare/lokalise': typeof LocaleCompareLokaliseRoute
  '/$locale/compare/phrase': typeof LocaleComparePhraseRoute
  '/$locale/compare/transifex': typeof LocaleCompareTransifexRoute
  '/$locale/i18n/angular': typeof LocaleI18nAngularRoute
  '/$locale/i18n/best-library': typeof LocaleI18nBestLibraryRoute
  '/$locale/i18n/best-tms': typeof LocaleI18nBestTmsRoute
  '/$locale/i18n/content-localization': typeof LocaleI18nContentLocalizationRoute
  '/$locale/i18n/content-localization-services': typeof LocaleI18nContentLocalizationServicesRoute
  '/$locale/i18n/cultural-adaptation': typeof LocaleI18nCulturalAdaptationRoute
  '/$locale/i18n/ecommerce-global-seo': typeof LocaleI18nEcommerceGlobalSeoRoute
  '/$locale/i18n/for-developers': typeof LocaleI18nForDevelopersRoute
  '/$locale/i18n/global-market-seo': typeof LocaleI18nGlobalMarketSeoRoute
  '/$locale/i18n/international-seo': typeof LocaleI18nInternationalSeoRoute
  '/$locale/i18n/international-seo-consulting': typeof LocaleI18nInternationalSeoConsultingRoute
  '/$locale/i18n/local-seo-international': typeof LocaleI18nLocalSeoInternationalRoute
  '/$locale/i18n/localization-management': typeof LocaleI18nLocalizationManagementRoute
  '/$locale/i18n/localization-platforms': typeof LocaleI18nLocalizationPlatformsRoute
  '/$locale/i18n/localization-software': typeof LocaleI18nLocalizationSoftwareRoute
  '/$locale/i18n/localization-tools': typeof LocaleI18nLocalizationToolsRoute
  '/$locale/i18n/localization-vs-internationalization': typeof LocaleI18nLocalizationVsInternationalizationRoute
  '/$locale/i18n/multilingual-seo': typeof LocaleI18nMultilingualSeoRoute
  '/$locale/i18n/multilingual-website-seo': typeof LocaleI18nMultilingualWebsiteSeoRoute
  '/$locale/i18n/nextjs': typeof LocaleI18nNextjsRoute
  '/$locale/i18n/nuxt': typeof LocaleI18nNuxtRoute
  '/$locale/i18n/react': typeof LocaleI18nReactRoute
  '/$locale/i18n/react-intl': typeof LocaleI18nReactIntlRoute
  '/$locale/i18n/seo-international-audiences': typeof LocaleI18nSeoInternationalAudiencesRoute
  '/$locale/i18n/software-localization': typeof LocaleI18nSoftwareLocalizationRoute
  '/$locale/i18n/software-localization-services': typeof LocaleI18nSoftwareLocalizationServicesRoute
  '/$locale/i18n/svelte': typeof LocaleI18nSvelteRoute
  '/$locale/i18n/technical-international-seo': typeof LocaleI18nTechnicalInternationalSeoRoute
  '/$locale/i18n/technical-multilingual-seo': typeof LocaleI18nTechnicalMultilingualSeoRoute
  '/$locale/i18n/translation-management-system': typeof LocaleI18nTranslationManagementSystemRoute
  '/$locale/i18n/translation-solutions': typeof LocaleI18nTranslationSolutionsRoute
  '/$locale/i18n/vue': typeof LocaleI18nVueRoute
  '/$locale/i18n/website-localization': typeof LocaleI18nWebsiteLocalizationRoute
  '/$locale/i18n/website-translation': typeof LocaleI18nWebsiteTranslationRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/compare': typeof LocaleCompareIndexRoute
  '/$locale/i18n': typeof LocaleI18nIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/features': typeof LocaleFeaturesRoute
  '/$locale/for-developers': typeof LocaleForDevelopersRoute
  '/$locale/for-product-teams': typeof LocaleForProductTeamsRoute
  '/$locale/for-translators': typeof LocaleForTranslatorsRoute
  '/$locale/integrations': typeof LocaleIntegrationsRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/status': typeof LocaleStatusRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/what-is': typeof LocaleWhatIsRoute
  '/$locale/what-is-internationalization': typeof LocaleWhatIsInternationalizationRoute
  '/$locale/what-is-localization': typeof LocaleWhatIsLocalizationRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/status': typeof ApiStatusRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/compare/crowdin': typeof LocaleCompareCrowdinRoute
  '/$locale/compare/lokalise': typeof LocaleCompareLokaliseRoute
  '/$locale/compare/phrase': typeof LocaleComparePhraseRoute
  '/$locale/compare/transifex': typeof LocaleCompareTransifexRoute
  '/$locale/i18n/angular': typeof LocaleI18nAngularRoute
  '/$locale/i18n/best-library': typeof LocaleI18nBestLibraryRoute
  '/$locale/i18n/best-tms': typeof LocaleI18nBestTmsRoute
  '/$locale/i18n/content-localization': typeof LocaleI18nContentLocalizationRoute
  '/$locale/i18n/content-localization-services': typeof LocaleI18nContentLocalizationServicesRoute
  '/$locale/i18n/cultural-adaptation': typeof LocaleI18nCulturalAdaptationRoute
  '/$locale/i18n/ecommerce-global-seo': typeof LocaleI18nEcommerceGlobalSeoRoute
  '/$locale/i18n/for-developers': typeof LocaleI18nForDevelopersRoute
  '/$locale/i18n/global-market-seo': typeof LocaleI18nGlobalMarketSeoRoute
  '/$locale/i18n/international-seo': typeof LocaleI18nInternationalSeoRoute
  '/$locale/i18n/international-seo-consulting': typeof LocaleI18nInternationalSeoConsultingRoute
  '/$locale/i18n/local-seo-international': typeof LocaleI18nLocalSeoInternationalRoute
  '/$locale/i18n/localization-management': typeof LocaleI18nLocalizationManagementRoute
  '/$locale/i18n/localization-platforms': typeof LocaleI18nLocalizationPlatformsRoute
  '/$locale/i18n/localization-software': typeof LocaleI18nLocalizationSoftwareRoute
  '/$locale/i18n/localization-tools': typeof LocaleI18nLocalizationToolsRoute
  '/$locale/i18n/localization-vs-internationalization': typeof LocaleI18nLocalizationVsInternationalizationRoute
  '/$locale/i18n/multilingual-seo': typeof LocaleI18nMultilingualSeoRoute
  '/$locale/i18n/multilingual-website-seo': typeof LocaleI18nMultilingualWebsiteSeoRoute
  '/$locale/i18n/nextjs': typeof LocaleI18nNextjsRoute
  '/$locale/i18n/nuxt': typeof LocaleI18nNuxtRoute
  '/$locale/i18n/react': typeof LocaleI18nReactRoute
  '/$locale/i18n/react-intl': typeof LocaleI18nReactIntlRoute
  '/$locale/i18n/seo-international-audiences': typeof LocaleI18nSeoInternationalAudiencesRoute
  '/$locale/i18n/software-localization': typeof LocaleI18nSoftwareLocalizationRoute
  '/$locale/i18n/software-localization-services': typeof LocaleI18nSoftwareLocalizationServicesRoute
  '/$locale/i18n/svelte': typeof LocaleI18nSvelteRoute
  '/$locale/i18n/technical-international-seo': typeof LocaleI18nTechnicalInternationalSeoRoute
  '/$locale/i18n/technical-multilingual-seo': typeof LocaleI18nTechnicalMultilingualSeoRoute
  '/$locale/i18n/translation-management-system': typeof LocaleI18nTranslationManagementSystemRoute
  '/$locale/i18n/translation-solutions': typeof LocaleI18nTranslationSolutionsRoute
  '/$locale/i18n/vue': typeof LocaleI18nVueRoute
  '/$locale/i18n/website-localization': typeof LocaleI18nWebsiteLocalizationRoute
  '/$locale/i18n/website-translation': typeof LocaleI18nWebsiteTranslationRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/compare/': typeof LocaleCompareIndexRoute
  '/$locale/i18n/': typeof LocaleI18nIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/changelog'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/$locale/about'
    | '/$locale/careers'
    | '/$locale/changelog'
    | '/$locale/features'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/integrations'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/status'
    | '/$locale/terms'
    | '/$locale/what-is'
    | '/$locale/what-is-internationalization'
    | '/$locale/what-is-localization'
    | '/api/changelog'
    | '/api/status'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/compare/crowdin'
    | '/$locale/compare/lokalise'
    | '/$locale/compare/phrase'
    | '/$locale/compare/transifex'
    | '/$locale/i18n/angular'
    | '/$locale/i18n/best-library'
    | '/$locale/i18n/best-tms'
    | '/$locale/i18n/content-localization'
    | '/$locale/i18n/content-localization-services'
    | '/$locale/i18n/cultural-adaptation'
    | '/$locale/i18n/ecommerce-global-seo'
    | '/$locale/i18n/for-developers'
    | '/$locale/i18n/global-market-seo'
    | '/$locale/i18n/international-seo'
    | '/$locale/i18n/international-seo-consulting'
    | '/$locale/i18n/local-seo-international'
    | '/$locale/i18n/localization-management'
    | '/$locale/i18n/localization-platforms'
    | '/$locale/i18n/localization-software'
    | '/$locale/i18n/localization-tools'
    | '/$locale/i18n/localization-vs-internationalization'
    | '/$locale/i18n/multilingual-seo'
    | '/$locale/i18n/multilingual-website-seo'
    | '/$locale/i18n/nextjs'
    | '/$locale/i18n/nuxt'
    | '/$locale/i18n/react'
    | '/$locale/i18n/react-intl'
    | '/$locale/i18n/seo-international-audiences'
    | '/$locale/i18n/software-localization'
    | '/$locale/i18n/software-localization-services'
    | '/$locale/i18n/svelte'
    | '/$locale/i18n/technical-international-seo'
    | '/$locale/i18n/technical-multilingual-seo'
    | '/$locale/i18n/translation-management-system'
    | '/$locale/i18n/translation-solutions'
    | '/$locale/i18n/vue'
    | '/$locale/i18n/website-localization'
    | '/$locale/i18n/website-translation'
    | '/$locale/blog'
    | '/$locale/compare'
    | '/$locale/i18n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/changelog'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/$locale/about'
    | '/$locale/careers'
    | '/$locale/changelog'
    | '/$locale/features'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/integrations'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/status'
    | '/$locale/terms'
    | '/$locale/what-is'
    | '/$locale/what-is-internationalization'
    | '/$locale/what-is-localization'
    | '/api/changelog'
    | '/api/status'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/compare/crowdin'
    | '/$locale/compare/lokalise'
    | '/$locale/compare/phrase'
    | '/$locale/compare/transifex'
    | '/$locale/i18n/angular'
    | '/$locale/i18n/best-library'
    | '/$locale/i18n/best-tms'
    | '/$locale/i18n/content-localization'
    | '/$locale/i18n/content-localization-services'
    | '/$locale/i18n/cultural-adaptation'
    | '/$locale/i18n/ecommerce-global-seo'
    | '/$locale/i18n/for-developers'
    | '/$locale/i18n/global-market-seo'
    | '/$locale/i18n/international-seo'
    | '/$locale/i18n/international-seo-consulting'
    | '/$locale/i18n/local-seo-international'
    | '/$locale/i18n/localization-management'
    | '/$locale/i18n/localization-platforms'
    | '/$locale/i18n/localization-software'
    | '/$locale/i18n/localization-tools'
    | '/$locale/i18n/localization-vs-internationalization'
    | '/$locale/i18n/multilingual-seo'
    | '/$locale/i18n/multilingual-website-seo'
    | '/$locale/i18n/nextjs'
    | '/$locale/i18n/nuxt'
    | '/$locale/i18n/react'
    | '/$locale/i18n/react-intl'
    | '/$locale/i18n/seo-international-audiences'
    | '/$locale/i18n/software-localization'
    | '/$locale/i18n/software-localization-services'
    | '/$locale/i18n/svelte'
    | '/$locale/i18n/technical-international-seo'
    | '/$locale/i18n/technical-multilingual-seo'
    | '/$locale/i18n/translation-management-system'
    | '/$locale/i18n/translation-solutions'
    | '/$locale/i18n/vue'
    | '/$locale/i18n/website-localization'
    | '/$locale/i18n/website-translation'
    | '/$locale/blog'
    | '/$locale/compare'
    | '/$locale/i18n'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/changelog'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/$locale/about'
    | '/$locale/careers'
    | '/$locale/changelog'
    | '/$locale/features'
    | '/$locale/for-developers'
    | '/$locale/for-product-teams'
    | '/$locale/for-translators'
    | '/$locale/integrations'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/status'
    | '/$locale/terms'
    | '/$locale/what-is'
    | '/$locale/what-is-internationalization'
    | '/$locale/what-is-localization'
    | '/api/changelog'
    | '/api/status'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/compare/crowdin'
    | '/$locale/compare/lokalise'
    | '/$locale/compare/phrase'
    | '/$locale/compare/transifex'
    | '/$locale/i18n/angular'
    | '/$locale/i18n/best-library'
    | '/$locale/i18n/best-tms'
    | '/$locale/i18n/content-localization'
    | '/$locale/i18n/content-localization-services'
    | '/$locale/i18n/cultural-adaptation'
    | '/$locale/i18n/ecommerce-global-seo'
    | '/$locale/i18n/for-developers'
    | '/$locale/i18n/global-market-seo'
    | '/$locale/i18n/international-seo'
    | '/$locale/i18n/international-seo-consulting'
    | '/$locale/i18n/local-seo-international'
    | '/$locale/i18n/localization-management'
    | '/$locale/i18n/localization-platforms'
    | '/$locale/i18n/localization-software'
    | '/$locale/i18n/localization-tools'
    | '/$locale/i18n/localization-vs-internationalization'
    | '/$locale/i18n/multilingual-seo'
    | '/$locale/i18n/multilingual-website-seo'
    | '/$locale/i18n/nextjs'
    | '/$locale/i18n/nuxt'
    | '/$locale/i18n/react'
    | '/$locale/i18n/react-intl'
    | '/$locale/i18n/seo-international-audiences'
    | '/$locale/i18n/software-localization'
    | '/$locale/i18n/software-localization-services'
    | '/$locale/i18n/svelte'
    | '/$locale/i18n/technical-international-seo'
    | '/$locale/i18n/technical-multilingual-seo'
    | '/$locale/i18n/translation-management-system'
    | '/$locale/i18n/translation-solutions'
    | '/$locale/i18n/vue'
    | '/$locale/i18n/website-localization'
    | '/$locale/i18n/website-translation'
    | '/$locale/blog/'
    | '/$locale/compare/'
    | '/$locale/i18n/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  FeaturesRoute: typeof FeaturesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleCareersRoute: typeof LocaleCareersRoute
  LocaleChangelogRoute: typeof LocaleChangelogRoute
  LocaleFeaturesRoute: typeof LocaleFeaturesRoute
  LocaleForDevelopersRoute: typeof LocaleForDevelopersRoute
  LocaleForProductTeamsRoute: typeof LocaleForProductTeamsRoute
  LocaleForTranslatorsRoute: typeof LocaleForTranslatorsRoute
  LocaleIntegrationsRoute: typeof LocaleIntegrationsRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleStatusRoute: typeof LocaleStatusRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleWhatIsRoute: typeof LocaleWhatIsRoute
  LocaleWhatIsInternationalizationRoute: typeof LocaleWhatIsInternationalizationRoute
  LocaleWhatIsLocalizationRoute: typeof LocaleWhatIsLocalizationRoute
  ApiChangelogRoute: typeof ApiChangelogRoute
  ApiStatusRoute: typeof ApiStatusRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleCompareCrowdinRoute: typeof LocaleCompareCrowdinRoute
  LocaleCompareLokaliseRoute: typeof LocaleCompareLokaliseRoute
  LocaleComparePhraseRoute: typeof LocaleComparePhraseRoute
  LocaleCompareTransifexRoute: typeof LocaleCompareTransifexRoute
  LocaleI18nAngularRoute: typeof LocaleI18nAngularRoute
  LocaleI18nBestLibraryRoute: typeof LocaleI18nBestLibraryRoute
  LocaleI18nBestTmsRoute: typeof LocaleI18nBestTmsRoute
  LocaleI18nContentLocalizationRoute: typeof LocaleI18nContentLocalizationRoute
  LocaleI18nContentLocalizationServicesRoute: typeof LocaleI18nContentLocalizationServicesRoute
  LocaleI18nCulturalAdaptationRoute: typeof LocaleI18nCulturalAdaptationRoute
  LocaleI18nEcommerceGlobalSeoRoute: typeof LocaleI18nEcommerceGlobalSeoRoute
  LocaleI18nForDevelopersRoute: typeof LocaleI18nForDevelopersRoute
  LocaleI18nGlobalMarketSeoRoute: typeof LocaleI18nGlobalMarketSeoRoute
  LocaleI18nInternationalSeoRoute: typeof LocaleI18nInternationalSeoRoute
  LocaleI18nInternationalSeoConsultingRoute: typeof LocaleI18nInternationalSeoConsultingRoute
  LocaleI18nLocalSeoInternationalRoute: typeof LocaleI18nLocalSeoInternationalRoute
  LocaleI18nLocalizationManagementRoute: typeof LocaleI18nLocalizationManagementRoute
  LocaleI18nLocalizationPlatformsRoute: typeof LocaleI18nLocalizationPlatformsRoute
  LocaleI18nLocalizationSoftwareRoute: typeof LocaleI18nLocalizationSoftwareRoute
  LocaleI18nLocalizationToolsRoute: typeof LocaleI18nLocalizationToolsRoute
  LocaleI18nLocalizationVsInternationalizationRoute: typeof LocaleI18nLocalizationVsInternationalizationRoute
  LocaleI18nMultilingualSeoRoute: typeof LocaleI18nMultilingualSeoRoute
  LocaleI18nMultilingualWebsiteSeoRoute: typeof LocaleI18nMultilingualWebsiteSeoRoute
  LocaleI18nNextjsRoute: typeof LocaleI18nNextjsRoute
  LocaleI18nNuxtRoute: typeof LocaleI18nNuxtRoute
  LocaleI18nReactRoute: typeof LocaleI18nReactRoute
  LocaleI18nReactIntlRoute: typeof LocaleI18nReactIntlRoute
  LocaleI18nSeoInternationalAudiencesRoute: typeof LocaleI18nSeoInternationalAudiencesRoute
  LocaleI18nSoftwareLocalizationRoute: typeof LocaleI18nSoftwareLocalizationRoute
  LocaleI18nSoftwareLocalizationServicesRoute: typeof LocaleI18nSoftwareLocalizationServicesRoute
  LocaleI18nSvelteRoute: typeof LocaleI18nSvelteRoute
  LocaleI18nTechnicalInternationalSeoRoute: typeof LocaleI18nTechnicalInternationalSeoRoute
  LocaleI18nTechnicalMultilingualSeoRoute: typeof LocaleI18nTechnicalMultilingualSeoRoute
  LocaleI18nTranslationManagementSystemRoute: typeof LocaleI18nTranslationManagementSystemRoute
  LocaleI18nTranslationSolutionsRoute: typeof LocaleI18nTranslationSolutionsRoute
  LocaleI18nVueRoute: typeof LocaleI18nVueRoute
  LocaleI18nWebsiteLocalizationRoute: typeof LocaleI18nWebsiteLocalizationRoute
  LocaleI18nWebsiteTranslationRoute: typeof LocaleI18nWebsiteTranslationRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleCompareIndexRoute: typeof LocaleCompareIndexRoute
  LocaleI18nIndexRoute: typeof LocaleI18nIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog': {
      id: '/api/changelog'
      path: '/api/changelog'
      fullPath: '/api/changelog'
      preLoaderRoute: typeof ApiChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/what-is-localization': {
      id: '/$locale/what-is-localization'
      path: '/$locale/what-is-localization'
      fullPath: '/$locale/what-is-localization'
      preLoaderRoute: typeof LocaleWhatIsLocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/what-is-internationalization': {
      id: '/$locale/what-is-internationalization'
      path: '/$locale/what-is-internationalization'
      fullPath: '/$locale/what-is-internationalization'
      preLoaderRoute: typeof LocaleWhatIsInternationalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/what-is': {
      id: '/$locale/what-is'
      path: '/$locale/what-is'
      fullPath: '/$locale/what-is'
      preLoaderRoute: typeof LocaleWhatIsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/$locale/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/status': {
      id: '/$locale/status'
      path: '/$locale/status'
      fullPath: '/$locale/status'
      preLoaderRoute: typeof LocaleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/$locale/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/$locale/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/integrations': {
      id: '/$locale/integrations'
      path: '/$locale/integrations'
      fullPath: '/$locale/integrations'
      preLoaderRoute: typeof LocaleIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-translators': {
      id: '/$locale/for-translators'
      path: '/$locale/for-translators'
      fullPath: '/$locale/for-translators'
      preLoaderRoute: typeof LocaleForTranslatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-product-teams': {
      id: '/$locale/for-product-teams'
      path: '/$locale/for-product-teams'
      fullPath: '/$locale/for-product-teams'
      preLoaderRoute: typeof LocaleForProductTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/for-developers': {
      id: '/$locale/for-developers'
      path: '/$locale/for-developers'
      fullPath: '/$locale/for-developers'
      preLoaderRoute: typeof LocaleForDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/features': {
      id: '/$locale/features'
      path: '/$locale/features'
      fullPath: '/$locale/features'
      preLoaderRoute: typeof LocaleFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/changelog': {
      id: '/$locale/changelog'
      path: '/$locale/changelog'
      fullPath: '/$locale/changelog'
      preLoaderRoute: typeof LocaleChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/careers': {
      id: '/$locale/careers'
      path: '/$locale/careers'
      fullPath: '/$locale/careers'
      preLoaderRoute: typeof LocaleCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/': {
      id: '/$locale/i18n/'
      path: '/$locale/i18n'
      fullPath: '/$locale/i18n'
      preLoaderRoute: typeof LocaleI18nIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare/': {
      id: '/$locale/compare/'
      path: '/$locale/compare'
      fullPath: '/$locale/compare'
      preLoaderRoute: typeof LocaleCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/$locale/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/website-translation': {
      id: '/$locale/i18n/website-translation'
      path: '/$locale/i18n/website-translation'
      fullPath: '/$locale/i18n/website-translation'
      preLoaderRoute: typeof LocaleI18nWebsiteTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/website-localization': {
      id: '/$locale/i18n/website-localization'
      path: '/$locale/i18n/website-localization'
      fullPath: '/$locale/i18n/website-localization'
      preLoaderRoute: typeof LocaleI18nWebsiteLocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/vue': {
      id: '/$locale/i18n/vue'
      path: '/$locale/i18n/vue'
      fullPath: '/$locale/i18n/vue'
      preLoaderRoute: typeof LocaleI18nVueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/translation-solutions': {
      id: '/$locale/i18n/translation-solutions'
      path: '/$locale/i18n/translation-solutions'
      fullPath: '/$locale/i18n/translation-solutions'
      preLoaderRoute: typeof LocaleI18nTranslationSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/translation-management-system': {
      id: '/$locale/i18n/translation-management-system'
      path: '/$locale/i18n/translation-management-system'
      fullPath: '/$locale/i18n/translation-management-system'
      preLoaderRoute: typeof LocaleI18nTranslationManagementSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/technical-multilingual-seo': {
      id: '/$locale/i18n/technical-multilingual-seo'
      path: '/$locale/i18n/technical-multilingual-seo'
      fullPath: '/$locale/i18n/technical-multilingual-seo'
      preLoaderRoute: typeof LocaleI18nTechnicalMultilingualSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/technical-international-seo': {
      id: '/$locale/i18n/technical-international-seo'
      path: '/$locale/i18n/technical-international-seo'
      fullPath: '/$locale/i18n/technical-international-seo'
      preLoaderRoute: typeof LocaleI18nTechnicalInternationalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/svelte': {
      id: '/$locale/i18n/svelte'
      path: '/$locale/i18n/svelte'
      fullPath: '/$locale/i18n/svelte'
      preLoaderRoute: typeof LocaleI18nSvelteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/software-localization-services': {
      id: '/$locale/i18n/software-localization-services'
      path: '/$locale/i18n/software-localization-services'
      fullPath: '/$locale/i18n/software-localization-services'
      preLoaderRoute: typeof LocaleI18nSoftwareLocalizationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/software-localization': {
      id: '/$locale/i18n/software-localization'
      path: '/$locale/i18n/software-localization'
      fullPath: '/$locale/i18n/software-localization'
      preLoaderRoute: typeof LocaleI18nSoftwareLocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/seo-international-audiences': {
      id: '/$locale/i18n/seo-international-audiences'
      path: '/$locale/i18n/seo-international-audiences'
      fullPath: '/$locale/i18n/seo-international-audiences'
      preLoaderRoute: typeof LocaleI18nSeoInternationalAudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/react-intl': {
      id: '/$locale/i18n/react-intl'
      path: '/$locale/i18n/react-intl'
      fullPath: '/$locale/i18n/react-intl'
      preLoaderRoute: typeof LocaleI18nReactIntlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/react': {
      id: '/$locale/i18n/react'
      path: '/$locale/i18n/react'
      fullPath: '/$locale/i18n/react'
      preLoaderRoute: typeof LocaleI18nReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/nuxt': {
      id: '/$locale/i18n/nuxt'
      path: '/$locale/i18n/nuxt'
      fullPath: '/$locale/i18n/nuxt'
      preLoaderRoute: typeof LocaleI18nNuxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/nextjs': {
      id: '/$locale/i18n/nextjs'
      path: '/$locale/i18n/nextjs'
      fullPath: '/$locale/i18n/nextjs'
      preLoaderRoute: typeof LocaleI18nNextjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/multilingual-website-seo': {
      id: '/$locale/i18n/multilingual-website-seo'
      path: '/$locale/i18n/multilingual-website-seo'
      fullPath: '/$locale/i18n/multilingual-website-seo'
      preLoaderRoute: typeof LocaleI18nMultilingualWebsiteSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/multilingual-seo': {
      id: '/$locale/i18n/multilingual-seo'
      path: '/$locale/i18n/multilingual-seo'
      fullPath: '/$locale/i18n/multilingual-seo'
      preLoaderRoute: typeof LocaleI18nMultilingualSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/localization-vs-internationalization': {
      id: '/$locale/i18n/localization-vs-internationalization'
      path: '/$locale/i18n/localization-vs-internationalization'
      fullPath: '/$locale/i18n/localization-vs-internationalization'
      preLoaderRoute: typeof LocaleI18nLocalizationVsInternationalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/localization-tools': {
      id: '/$locale/i18n/localization-tools'
      path: '/$locale/i18n/localization-tools'
      fullPath: '/$locale/i18n/localization-tools'
      preLoaderRoute: typeof LocaleI18nLocalizationToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/localization-software': {
      id: '/$locale/i18n/localization-software'
      path: '/$locale/i18n/localization-software'
      fullPath: '/$locale/i18n/localization-software'
      preLoaderRoute: typeof LocaleI18nLocalizationSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/localization-platforms': {
      id: '/$locale/i18n/localization-platforms'
      path: '/$locale/i18n/localization-platforms'
      fullPath: '/$locale/i18n/localization-platforms'
      preLoaderRoute: typeof LocaleI18nLocalizationPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/localization-management': {
      id: '/$locale/i18n/localization-management'
      path: '/$locale/i18n/localization-management'
      fullPath: '/$locale/i18n/localization-management'
      preLoaderRoute: typeof LocaleI18nLocalizationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/local-seo-international': {
      id: '/$locale/i18n/local-seo-international'
      path: '/$locale/i18n/local-seo-international'
      fullPath: '/$locale/i18n/local-seo-international'
      preLoaderRoute: typeof LocaleI18nLocalSeoInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/international-seo-consulting': {
      id: '/$locale/i18n/international-seo-consulting'
      path: '/$locale/i18n/international-seo-consulting'
      fullPath: '/$locale/i18n/international-seo-consulting'
      preLoaderRoute: typeof LocaleI18nInternationalSeoConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/international-seo': {
      id: '/$locale/i18n/international-seo'
      path: '/$locale/i18n/international-seo'
      fullPath: '/$locale/i18n/international-seo'
      preLoaderRoute: typeof LocaleI18nInternationalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/global-market-seo': {
      id: '/$locale/i18n/global-market-seo'
      path: '/$locale/i18n/global-market-seo'
      fullPath: '/$locale/i18n/global-market-seo'
      preLoaderRoute: typeof LocaleI18nGlobalMarketSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/for-developers': {
      id: '/$locale/i18n/for-developers'
      path: '/$locale/i18n/for-developers'
      fullPath: '/$locale/i18n/for-developers'
      preLoaderRoute: typeof LocaleI18nForDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/ecommerce-global-seo': {
      id: '/$locale/i18n/ecommerce-global-seo'
      path: '/$locale/i18n/ecommerce-global-seo'
      fullPath: '/$locale/i18n/ecommerce-global-seo'
      preLoaderRoute: typeof LocaleI18nEcommerceGlobalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/cultural-adaptation': {
      id: '/$locale/i18n/cultural-adaptation'
      path: '/$locale/i18n/cultural-adaptation'
      fullPath: '/$locale/i18n/cultural-adaptation'
      preLoaderRoute: typeof LocaleI18nCulturalAdaptationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/content-localization-services': {
      id: '/$locale/i18n/content-localization-services'
      path: '/$locale/i18n/content-localization-services'
      fullPath: '/$locale/i18n/content-localization-services'
      preLoaderRoute: typeof LocaleI18nContentLocalizationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/content-localization': {
      id: '/$locale/i18n/content-localization'
      path: '/$locale/i18n/content-localization'
      fullPath: '/$locale/i18n/content-localization'
      preLoaderRoute: typeof LocaleI18nContentLocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/best-tms': {
      id: '/$locale/i18n/best-tms'
      path: '/$locale/i18n/best-tms'
      fullPath: '/$locale/i18n/best-tms'
      preLoaderRoute: typeof LocaleI18nBestTmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/best-library': {
      id: '/$locale/i18n/best-library'
      path: '/$locale/i18n/best-library'
      fullPath: '/$locale/i18n/best-library'
      preLoaderRoute: typeof LocaleI18nBestLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/i18n/angular': {
      id: '/$locale/i18n/angular'
      path: '/$locale/i18n/angular'
      fullPath: '/$locale/i18n/angular'
      preLoaderRoute: typeof LocaleI18nAngularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare/transifex': {
      id: '/$locale/compare/transifex'
      path: '/$locale/compare/transifex'
      fullPath: '/$locale/compare/transifex'
      preLoaderRoute: typeof LocaleCompareTransifexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare/phrase': {
      id: '/$locale/compare/phrase'
      path: '/$locale/compare/phrase'
      fullPath: '/$locale/compare/phrase'
      preLoaderRoute: typeof LocaleComparePhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare/lokalise': {
      id: '/$locale/compare/lokalise'
      path: '/$locale/compare/lokalise'
      fullPath: '/$locale/compare/lokalise'
      preLoaderRoute: typeof LocaleCompareLokaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare/crowdin': {
      id: '/$locale/compare/crowdin'
      path: '/$locale/compare/crowdin'
      fullPath: '/$locale/compare/crowdin'
      preLoaderRoute: typeof LocaleCompareCrowdinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  FeaturesRoute: FeaturesRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleCareersRoute: LocaleCareersRoute,
  LocaleChangelogRoute: LocaleChangelogRoute,
  LocaleFeaturesRoute: LocaleFeaturesRoute,
  LocaleForDevelopersRoute: LocaleForDevelopersRoute,
  LocaleForProductTeamsRoute: LocaleForProductTeamsRoute,
  LocaleForTranslatorsRoute: LocaleForTranslatorsRoute,
  LocaleIntegrationsRoute: LocaleIntegrationsRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleStatusRoute: LocaleStatusRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleWhatIsRoute: LocaleWhatIsRoute,
  LocaleWhatIsInternationalizationRoute: LocaleWhatIsInternationalizationRoute,
  LocaleWhatIsLocalizationRoute: LocaleWhatIsLocalizationRoute,
  ApiChangelogRoute: ApiChangelogRoute,
  ApiStatusRoute: ApiStatusRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleCompareCrowdinRoute: LocaleCompareCrowdinRoute,
  LocaleCompareLokaliseRoute: LocaleCompareLokaliseRoute,
  LocaleComparePhraseRoute: LocaleComparePhraseRoute,
  LocaleCompareTransifexRoute: LocaleCompareTransifexRoute,
  LocaleI18nAngularRoute: LocaleI18nAngularRoute,
  LocaleI18nBestLibraryRoute: LocaleI18nBestLibraryRoute,
  LocaleI18nBestTmsRoute: LocaleI18nBestTmsRoute,
  LocaleI18nContentLocalizationRoute: LocaleI18nContentLocalizationRoute,
  LocaleI18nContentLocalizationServicesRoute:
    LocaleI18nContentLocalizationServicesRoute,
  LocaleI18nCulturalAdaptationRoute: LocaleI18nCulturalAdaptationRoute,
  LocaleI18nEcommerceGlobalSeoRoute: LocaleI18nEcommerceGlobalSeoRoute,
  LocaleI18nForDevelopersRoute: LocaleI18nForDevelopersRoute,
  LocaleI18nGlobalMarketSeoRoute: LocaleI18nGlobalMarketSeoRoute,
  LocaleI18nInternationalSeoRoute: LocaleI18nInternationalSeoRoute,
  LocaleI18nInternationalSeoConsultingRoute:
    LocaleI18nInternationalSeoConsultingRoute,
  LocaleI18nLocalSeoInternationalRoute: LocaleI18nLocalSeoInternationalRoute,
  LocaleI18nLocalizationManagementRoute: LocaleI18nLocalizationManagementRoute,
  LocaleI18nLocalizationPlatformsRoute: LocaleI18nLocalizationPlatformsRoute,
  LocaleI18nLocalizationSoftwareRoute: LocaleI18nLocalizationSoftwareRoute,
  LocaleI18nLocalizationToolsRoute: LocaleI18nLocalizationToolsRoute,
  LocaleI18nLocalizationVsInternationalizationRoute:
    LocaleI18nLocalizationVsInternationalizationRoute,
  LocaleI18nMultilingualSeoRoute: LocaleI18nMultilingualSeoRoute,
  LocaleI18nMultilingualWebsiteSeoRoute: LocaleI18nMultilingualWebsiteSeoRoute,
  LocaleI18nNextjsRoute: LocaleI18nNextjsRoute,
  LocaleI18nNuxtRoute: LocaleI18nNuxtRoute,
  LocaleI18nReactRoute: LocaleI18nReactRoute,
  LocaleI18nReactIntlRoute: LocaleI18nReactIntlRoute,
  LocaleI18nSeoInternationalAudiencesRoute:
    LocaleI18nSeoInternationalAudiencesRoute,
  LocaleI18nSoftwareLocalizationRoute: LocaleI18nSoftwareLocalizationRoute,
  LocaleI18nSoftwareLocalizationServicesRoute:
    LocaleI18nSoftwareLocalizationServicesRoute,
  LocaleI18nSvelteRoute: LocaleI18nSvelteRoute,
  LocaleI18nTechnicalInternationalSeoRoute:
    LocaleI18nTechnicalInternationalSeoRoute,
  LocaleI18nTechnicalMultilingualSeoRoute:
    LocaleI18nTechnicalMultilingualSeoRoute,
  LocaleI18nTranslationManagementSystemRoute:
    LocaleI18nTranslationManagementSystemRoute,
  LocaleI18nTranslationSolutionsRoute: LocaleI18nTranslationSolutionsRoute,
  LocaleI18nVueRoute: LocaleI18nVueRoute,
  LocaleI18nWebsiteLocalizationRoute: LocaleI18nWebsiteLocalizationRoute,
  LocaleI18nWebsiteTranslationRoute: LocaleI18nWebsiteTranslationRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleCompareIndexRoute: LocaleCompareIndexRoute,
  LocaleI18nIndexRoute: LocaleI18nIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
