/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocaleCollectionIndexRouteImport } from './routes/$locale/$collection/index'
import { Route as LocaleCollectionArticleRouteImport } from './routes/$locale/$collection/$article'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/$locale/faq',
  path: '/$locale/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCollectionIndexRoute = LocaleCollectionIndexRouteImport.update({
  id: '/$locale/$collection/',
  path: '/$locale/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCollectionArticleRoute = LocaleCollectionArticleRouteImport.update({
  id: '/$locale/$collection/$article',
  path: '/$locale/$collection/$article',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$collection/$article': typeof LocaleCollectionArticleRoute
  '/$locale/$collection': typeof LocaleCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$collection/$article': typeof LocaleCollectionArticleRoute
  '/$locale/$collection': typeof LocaleCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$collection/$article': typeof LocaleCollectionArticleRoute
  '/$locale/$collection/': typeof LocaleCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale/faq'
    | '/$locale'
    | '/$locale/$collection/$article'
    | '/$locale/$collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/faq'
    | '/$locale'
    | '/$locale/$collection/$article'
    | '/$locale/$collection'
  id:
    | '__root__'
    | '/'
    | '/$locale/faq'
    | '/$locale/'
    | '/$locale/$collection/$article'
    | '/$locale/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCollectionArticleRoute: typeof LocaleCollectionArticleRoute
  LocaleCollectionIndexRoute: typeof LocaleCollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/$locale/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$collection/': {
      id: '/$locale/$collection/'
      path: '/$locale/$collection'
      fullPath: '/$locale/$collection'
      preLoaderRoute: typeof LocaleCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$collection/$article': {
      id: '/$locale/$collection/$article'
      path: '/$locale/$collection/$article'
      fullPath: '/$locale/$collection/$article'
      preLoaderRoute: typeof LocaleCollectionArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCollectionArticleRoute: LocaleCollectionArticleRoute,
  LocaleCollectionIndexRoute: LocaleCollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
